//Auth
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_OUT_USER = "CLEAR_OUT_USER";
export const LOADING_USER = "LOADING_USER";
export const CONFIRMED_USER = "CONFIRMED_USER";
//Errors
export const GET_ERRORS = "GET_ERRORS";
//Message
export const GET_MESSAGE = "GET_MESSAGE";
//Projects
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_SELECTED_PROJECT = "GET_SELECTED_PROJECT";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const LOADING_PROJECT = "LOADING_PROJECT";
export const SELECT_COORDINATES = "SELECT_COORDINATES";

//Employess
export const GET_ALL_EMPLOYEES = "GET_ALL_EMPLOYEES";
export const GET_SELECTED_EMPLOYEE = "GET_SELECTED_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const ACTIVATION_EMPLOYEE = "ACTIVATION_EMPLOYEE";

//Loading
export const LOADING = "LOADING";
//Calendar
export const GET_SELECT_DAY = "GET_SELECT_DAY";
export const GET_SELECT_MONTH = "GET_SELECT_MONTH";
export const LOADING_JOBDAY = "LOADING_JOBDAY";
export const JOBDAY_MESSAGE = "JOBDAY_MESSAGE";
export const PICK_DATE = "PICK_DATE";
export const GET_STATUS = "GET_STATUS";
